### ISSUE TITLE
What if you add 2 more providers ?

### ISSUE THREAD

**Issue by DogancanYr** [Reddiepoint/MultiUp-Direct#1]
Mirrorace and mirrored sites are left, can you add them here? 
There are no other mirror upload sites other than these.

**Comment by Reddiepoint** [comment]
I'll have to rewrite the app again if I want to add more mirroring services. 

I don't think I'll be able to add them with the skills I have right now since the links aren't shown with a simple get request. I also need to be able to bypass the Cloudflare check for mirrorace.org and also find a way to get the links, since they go out of their way to stop scraping. Neither of them have an API that supports "anonymous" calls to get the file information either (they do have endpoints for getting files belonging to your account with an API key, but they are useless in this case).

**Comment by DogancanYr** [comment]
> I'll have to rewrite the app again if I want to add more mirroring services.
> 
> I don't think I'll be able to add them with the skills I have right now since the links aren't shown with a simple get request. I also need to be able to bypass the Cloudflare check for mirrorace.org and also find a way to get the links, since they go out of their way to stop scraping. Neither of them have an API that supports "anonymous" calls to get the file information either (they do have endpoints for getting files belonging to your account with an API key, but they are useless in this case).

Can you put an explanation here?

**Comment by Reddiepoint** [comment]
What do you want me to explain?

**Comment by DogancanYr** [comment]
As you did in RedAlt-SteamUp-Creator, put the url of cs.rin and write a description.

**Comment by Reddiepoint** [comment]
Ok, I'll do it later today
